/**
 * Generated by sync-artifacts.js — DO NOT EDIT MANUALLY.
 * Source: contracts_new/deployments/testnet/
 */

import _addresses from './addresses.json';
import abis from './abis.json';

const addresses = _addresses as Record<string, string>;

// Official HashKey Testnet USDC address (used when MockUSDC_EIP3009 is not deployed)
const OFFICIAL_USDC = '0x79AEc4EeA31D50792F61D1Ca0733C18c89524C9e';

export const CONTRACTS = {
  HashFlowEscrow: {
    address: addresses.HashFlowEscrow as `0x${string}`,
    abi: abis.HashFlowEscrow,
  },
  MockERC20: {
    // On HashKey Testnet the settlement token is the official USDC — no MockUSDC is deployed.
    // On local hardhat the MockUSDC_EIP3009 address is used.
    address: (addresses.MockUSDC_EIP3009 || OFFICIAL_USDC) as `0x${string}`,
    abi: abis.MockUSDC_EIP3009,
  },
  MockZKVerifier: {
    address: addresses.MockZKVerifier as `0x${string}`,
    abi: abis.MockZKVerifier,
  },
  MockVault: {
    address: addresses.MockVault as `0x${string}`,
    abi: abis.MockVault,
  },
  MockHSP: {
    address: addresses.MockHSP as `0x${string}`,
    abi: abis.MockHSP,
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;
