/**
 * Generated by sync-artifacts.js
 * DO NOT EDIT MANUALLY
 */

import addresses from './addresses.json';
import abis from './abis.json';

export const CONTRACTS = {
  HashFlowEscrow: {
    address: addresses.HashFlowEscrow as `0x${string}`,
    abi: abis.HashFlowEscrow,
  },
  MockERC20: {
    address: addresses.MockERC20 as `0x${string}`,
    abi: abis.MockERC20,
  },
  MockZKVerifier: {
    address: addresses.MockZKVerifier as `0x${string}`,
    abi: abis.MockZKVerifier,
  },
  MockVault: {
    address: addresses.MockVault as `0x${string}`,
    abi: abis.MockVault,
  },
  MockHSP: {
    address: addresses.MockHSP as `0x${string}`,
    abi: abis.MockHSP,
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;
