/**
 * Generated by sync-artifacts.js
 * DO NOT EDIT MANUALLY
 */

import _addresses from './addresses.json';
import abis from './abis.json';

const addresses = _addresses as Record<string, string>;

export const CONTRACTS = {
  HashFlowEscrow: {
    address: addresses.HashFlowEscrow as `0x${string}`,
    abi: abis.HashFlowEscrow,
  },
  MockERC20: {
    address: (addresses.MockERC20 || addresses.MockUSDC_EIP3009) as `0x${string}`,
    abi: abis.MockUSDC_EIP3009,
  },
  MockZKVerifier: {
    address: addresses.MockZKVerifier as `0x${string}`,
    abi: abis.MockZKVerifier,
  },
  MockVault: {
    address: addresses.MockVault as `0x${string}`,
    abi: abis.MockVault,
  },
  MockHSP: {
    address: addresses.MockHSP as `0x${string}`,
    abi: abis.MockHSP,
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;
